<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>70_예외처리의_정석_try_catch_finally와_즉시실행함수</title>
</head>
<body>
    <h1>예외처리</h1>
    
    <script>
        //실험적으로 에러를 발생시킬 함수
        function secretFn(pwd){

            console.log('secretFn() 함수 시작')
            
            if(pwd === undefined){
                // throw '비밀번호를 입력하지 않음. Error'
                
                //조금 더 상세한 에러정보를 보여준다.
                throw new Error('비밀번호를 입력하지 않음. Error');
                //에러가 발생했기때문에 여기서 끝남
            }

            console.log('secretFn() 함수 종료')
        }

        //메인함수를 즉시실행
        (function main(){

            try{
                //에러가 발생할만한 코드를 작성하는 구간
                secretFn();
            }catch(e){
                //에러 발생시에만 실행되는 구간
                console.log(e);
            }finally{
                //에러 발생과 상관없이 무조건 실행되는 구간
                console.log('예외처리 완료')
            }

            console.log('프로그램 종료');

        })();
    </script>
</body>
</html>